dist: trusty
sudo: required
language: ruby
rvm:
  - 2.2
git:
  submodules: false
before_install:
  - sudo apt update && sudo apt install -y shellcheck
  - gem install mdl
script:
  - ./tools/scripts/linter.sh
branches:
  only:
  - master
  - develop
notifications:
  recipients:
    - xiebowen@qiniu.com
  email:
    on_success: change
    on_failure: always
