kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ava
  name: alluxio-master-readonly-journal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 10Gi
