FROM zookeeper:3.4

RUN cat /etc/*-release

# RUN sed -i s/archive.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list && \
#     sed -i s/security.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list

RUN apk update && \
    apk add net-tools

COPY docker/zookeeper.entrypoint.sh /entrypoint.sh

ENTRYPOINT /entrypoint.sh
CMD ["sleep", "3600"]
