FROM ubuntu:16.04

RUN sed -i s/archive.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list && \
    sed -i s/security.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list

RUN apt-get update && \
	apt-get install -y --no-install-recommends software-properties-common && \
	apt-get update && \
	apt-get install -y --no-install-recommends \
	less vim curl tree \
        net-tools tcpdump lsof iptraf \
        python-dev python-pip \
	openjdk-8-jdk openjdk-8-jre-headless libfuse-dev && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN python --version

RUN PIP_INSTALL="pip --no-cache-dir install --upgrade --index-url https://pypi.doubanio.com/simple" &&  \
        $PIP_INSTALL setuptools && $PIP_INSTALL six requests && $PIP_INSTALL alluxio

ENV ALLUXIO_CLASSPATH="/opt/alluxio/lib/gson-2.2.4.jar:/opt/alluxio/lib/qiniu-java-sdk-7.2.11.jar:/opt/alluxio/lib/okhttp-3.10.0.jar:/opt/alluxio/lib/okio-1.14.0.jar:/opt/alluxio/lib/jackson-databind-2.9.5.jar:/opt/alluxio/lib/jackson-core-2.9.5.jar:/opt/alluxio/lib/jackson-annotations-2.9.5.jar"
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64


COPY .qiniurc /root/
RUN mkdir -p /root/bin && \
	curl http://atlab.ava-test.xbowen.com/tmp/tools/qrsctl -o /root/bin/qrsctl && \
	chmod +x /root/bin/qrsctl

RUN curl http://devtools.dl.atlab.ai/docker/PRC-tz -o /root/PRC-tz && \
	mv /root/PRC-tz /etc/localtime
ENV LC_ALL=C.UTF-8

ADD alluxio /opt/alluxio
ADD lib /opt/alluxio/lib
ADD train.txt /root/
ADD assembly /opt/alluxio/assembly

RUN mkdir -p /home
COPY .tools.sh /home/
ENV TERM=xterm
COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
