alluxio:
  - master_host: alluxio-dashboard-ocr.ava-prd.kegate-jq.cloudappl.com
    group: ocr
  - master_host: alluxio-dashboard-general-reg.ava-prd.kegate-jq.cloudappl.com
    group: general-reg
  - master_host: alluxio-dashboard-blademaster.ava-prd.kegate-jq.cloudappl.com
    group: blademaster
  - master_host: alluxio-dashboard-terror.ava-prd.kegate-jq.cloudappl.com
    group: terror
  - master_host: alluxio-dashboard-group-ava.ava-prd.kegate-jq.cloudappl.com
    group: group-ava
  - master_host: alluxio-dashboard-alg-pro.ava-prd.kegate-jq.cloudappl.com
    group: alg-pro
  - master_host: alluxio-dashboard-video-det.ava-prd.kegate-jq.cloudappl.com
    group: video-det
  - master_host: alluxio-dashboard-video.ava-prd.kegate-jq.cloudappl.com
    group: video
  - master_host: alluxio-dashboard.ava-prd.kegate-jq.cloudappl.com
    group: default
  - master_host: alluxio-dashboard-face.ava-prd.kegate-jq.cloudappl.com
    group: face
