kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: alluxio-monitor-group
  name: alluxio-monitor-group
  namespace: ava
spec:
  clusterIP: None
  ports:
    - name: alluxio-export
      port: 9996
      protocol: TCP
      targetPort: 9996
  selector:
      app: alluxio-monitor-group